#!/usr/bin/env python3

from cogapp import Cog

import os
from os.path import join

paths = []

# TODO: read .gitignore for paths to ignore

for root, dirs, files in os.walk('.'):
    for filename in files:
        if filename.endswith('.elm'):
            paths.append(join(root, filename))

Cog().main(['executable_path_is_irrelevant', '-p', 'from elm import *', '-r'] + paths)
